# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-30 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0004_auto_20200530_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 57, 35, 998014, tzinfo=utc)),
        ),
    ]
