# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-31 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0010_auto_20200531_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
