# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-30 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_auto_20200530_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 17, 54, 0, 975767, tzinfo=utc)),
        ),
    ]
