# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-30 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0009_auto_20200530_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
